#!/usr/bin/env bash

# The command's name
echo -e 'git add'

# the command's description
echo "The git add command is definitely one of the most used command in git as it adds changes made in the working directory to the staging area. What this means is that the command git add tells git that you want to include a file or update a file in the next commit.

Files added to the staging area via git add are actually waiting to be snapshot or committed via the git commit command. Once the files are added to the staging area via git add, the command git status can be used to view the state of the working directory and staging area."

echo "------------"

# the command's syntax
echo "Syntax:"
echo "git test argument1 argument2"
echo -e "\targument1: description of argument 1"
echo -e "\targument2: description of argument 2"
#   ...      etc

echo "------------"

# the command's usage examples
# example 1
echo "git add README.md file.txt"
echo "Will add all the specified files to the staging area."

# example 2
echo "git add ."
echo "This will recursively add all the file in the current directory and all subdirectories to the staging area."

echo "git add -A"
echo "Will add all files and paths in the repository to the staging area."


exit 0
