#!/usr/bin/bash

# The command's name
echo -e 'git branch'

# the command's description
echo "description here"

echo "------------"

# the command's syntax
echo "Syntax:"
echo "git test argument1 argument2"
echo -e "\targument1: description of argument 1"
echo -e "\targument2: description of argument 2"
#   ...      etc

echo "------------"

# the command's usage examples
# example 1
echo "git branch"
echo "List all the current branches in your repository"

# example 2
echo "git branch testing"
echo "Will create a branch named 'testing'"

# example 3
echo "git branch -d testing"
echo "Will delete the branch named 'testing'. If the branch has unmerged changes it will not be deleted."

# example 4
echo "git branch -D testing"
echo "-D executes a force delete on branch 'testing'. This means the branch will be deleted even if it has unmerged changes. This command will permanently throw away all of the commits associated with that line of development."

# example 5
echo "git branch -m awesome"
echo "This will rename the current branch to 'awesome'"


exit 0
