#!/usr/bin/env bash

# some formatting variables
bold="\033[1m"
underline="\033[4m"
normal="\033[0m"
# to use this formatting use 'echo -e'
# start formatting sequence with ${bold} or ${underline}
# and end it with ${normal}

# The command's name
echo -e "\n${bold}COMMAND NAME:${normal}"
echo -e "\n\t${bold}git branch${normal} - list, create, delete branches."

echo -e "\n------------"

# the command's description
echo -e "\n${bold}COMMAND DESCRIPTION:${normal}"
echo -e "\n\tSometimes you need to work on a separate feature for a project, or fix a bug"
echo -e "\twhich occasionally appeared during the development process. Developing something"
echo -e "\tnew is always risky, as well as bug fixing, something might go wrong, to make sure"
echo -e "\tunstable code is never committed to master branch, there is a 'git branch' command."
echo -e "\n\tBy using 'git branch' command, you can create a separate branch to work on, branch"
echo -e "\trepresents a copy of your main code base, but created with a special purpose."
echo -e "\tFurther after, being satisfied with the results, you are able to merge a branch into master."

echo -e "\n------------"

# the command's syntax
echo -e "\n${bold}COMMAND SYNTAX:${normal}"
echo -e "\n\tgit test argument1 argument2"
echo -e "\t\targument1: description of argument 1"
echo -e "\t\targument2: description of argument 2"
#   ...      etc

echo -e "\n------------"

# the command's usage examples
# example 1
echo -e "\n${bold}COMMAND EXAMPLES:${normal}"
echo -e "\n\t${underline}Example 1${normal}"
echo -e "\t\tgit test"
echo -e "\t\tdescription here"

# example 2
echo -e "\n\t${underline}Example 2${normal}"
echo -e "\t\tgit test something"
echo -e "\t\tdescription here\n"

#   ...      etc

exit 0
