#!/usr/bin/bash
echo "This is a test command."

# The command's name
echo -e 'git commit'

# the command's description
echo "git commit adds the latest version of your staged files to the project's version control. 

Commits are made to the local repository, not the remote repository (which would require to perform a git push)."

echo "------------"

# the command's syntax
echo "Syntax:"
echo "test argument1 argument2"
echo -e "\targument1: description of argument 1"
echo -e "\targument2: description of argument 2"
#   ...      etc

echo "------------"

# the command's usage examples
# example 1
echo "test"
echo description here

# example 2
echo "test something"
echo description here


exit 0
