#!/usr/bin/env bash

# some formatting variables
bold="\033[1m"
underline="\033[4m"
normal="\033[0m"
# to use this formatting use 'echo -e'
# start formatting sequence with ${bold} or ${underline}
# and end it with ${normal}

# The command's name
echo -e "\n${bold}COMMAND NAME:${normal}"
echo -e "\n\t${bold}git config${normal} - set repository / global Git defaults"

echo -e "\n------------"

# the command's description
echo -e "\n${bold}COMMAND DESCRIPTION:${normal}"
echo -e "\n\tWhen you have initialised a project, inside your repository, you will find a hidden"
echo -e "\tsubdirectory .git, it will contain all necessary metadata. In that folder, you will find a"
echo -e "\tconfiguration file (.git/config), which has a default configurations for this specific"
echo -e "\trepository (e.g. your username, preferred editor etc.)"
echo -e "\n\tCustomising can be also done globally by configuring a global (~/.gitconfig) file just "
echo -e "\tprovide a '—global' flag after the 'git config' command (e.g git config —global -e, this "
echo -e "\twill open a global gitconfig file in a text editor, which is ready for further configuration)."

echo -e "\n------------"

# the command's syntax
echo -e "\n${bold}COMMAND SYNTAX:${normal}"
echo -e "\n\tgit test argument1 argument2"
echo -e "\t\targument1: description of argument 1"
echo -e "\t\targument2: description of argument 2"
#   ...      etc

echo -e "\n------------"

# the command's usage examples
# example 1
echo -e "\n${bold}COMMAND EXAMPLES:${normal}"
echo -e "\n\t${underline}Example 1${normal}"
echo -e "\t\tgit test"
echo -e "\t\tdescription here"

# example 2
echo -e "\n\t${underline}Example 2${normal}"
echo -e "\t\tgit test something"
echo -e "\t\tdescription here\n"

#   ...      etc

exit 0
