#!/usr/bin/env bash
echo "This is the git config command."

# The command's name
echo -e 'git config'

# the command's description
echo "This command allows you to view and set options for a repository or the global git environment. The configuration options recognized by Git fall into two categories: client-side and server-side. The majority of the options are client-side – configuring a user's personal working preferences."

echo "------------"

# the command's syntax
echo "Syntax:"
echo "$ git config [file-option] [type] --add name value"
echo -e "$ git config --unset-all test: Remove all lines matching the key 'test' from config file."
echo -e "$ git config --get test: Get the value for a given key 'test'"
#   ...      etc

echo "------------"

# the command's usage examples
# example 1
echo "git config --global user.name 'John Smith'"
echo "Sets the user identification in the global context of Git; you can change this for specific projects by not specifying the --global flag"

# example 2
echo "git config --global core.editor 'vim'"
echo "Changes the default text editor to vim or any other program specified by the user"


exit 0
