#!/usr/bin/env bash

# The command's name
echo -e 'git diff'

# the command's description
echo "description here"

echo "------------"

# the command's syntax
echo "Syntax:"
echo "git diff upstream/master"
echo -e "\tupstream/master: The name of the branch to be compared to the current branch."

echo "------------"

# the command's usage examples
# example 1
echo "git test"
echo description here

# example 2
echo "git test something"
echo description here


exit 0
