#!/usr/bin/bash
echo "This is a test command."

# The command's name
echo -e 'git fetch'

# the command's description
echo "The git fetch command downloads commits from a remote repository into your local repository, without merging them as opposed to git pull. This allows for review of changes in the remote respository before adding them to your local repository."

echo "------------"

# the command's syntax
echo "Syntax:"
echo "test argument1 argument2"
echo -e "\targument1: description of argument 1"
echo -e "\targument2: description of argument 2"
#   ...      etc

echo "------------"

# the command's usage examples
# example 1
echo "test"
echo description here

# example 2
echo "test something"
echo description here


exit 0
