#!/usr/bin/env bash
echo "This is the git fetch command."

# The command's name
echo -e 'git fetch'

# the command's description
echo "Fetch and download branches from another repository."

echo "------------"

# the command's syntax
echo "Syntax:"
echo "git fetch [options] <repository>"
echo -e "\t--all: Fetches all remotes"
echo -e "\t--depth=<num>: Limit the number of commits to fetch from the remote repository"
#   ...      etc

echo "------------"

# the command's usage examples
# example 1
echo "git fetch origin"
echo "This command will copy all new branches and tags from the remote server (origin) and store them in your local repository."

# example 2
echo "git fetch origin +lists:references maint:compatiblity"
echo "This command updates or creates the branches references and compatibility in the local repository by fetching from the branches lists and maint respectively."


exit 0
