#!/usr/bin/env bash

# some formatting variables
bold="\033[1m"
underline="\033[4m"
normal="\033[0m"
# to use this formatting use 'echo -e'
# start formatting sequence with ${bold} or ${underline}
# and end it with ${normal}

# The command's name
echo -e "\n${bold}COMMAND NAME:${normal}"
echo -e "\n\t${bold}git commit${normal}"

echo -e "\n------------"

# the command's description
echo -e "\n${bold}COMMAND DESCRIPTION:${normal}"

echo -e "\n\tgit commit command commits the staged snapshot to the project history. Commited snapshots" 
echo -e "\tare safe versions of a project because Git will not change them unless the user ask it"
echo -e "\tto.Every project has 3 places:working directory, staging area and repository.The working are" 
echo -e "\tis the place where user change the files from repository. The staging are is a buffer area" 
echo -e "\tbetween the working directory and the project history. This area let user group related"
echo -e "\tchanges into a snapshot before committing it to the project history. git commit is moving a grouped snapshot of the modified files into repository."

echo -e "\n------------"

# the command's syntax
echo -e "\nCOMMAND SYNTAX:"
echo -e "\n\tgit commit [options] "
echo -e "\t\t-m <msg>:  Specify a message <msg> to be used as the commit message."
echo -e "\t\t-a: Stage files that have been deleted or modified automatically."

echo -e "\n------------"
