#!/usr/bin/env bash
echo -e git log
echo git log command shows all the commit logs.If it does not have any argument or flag, it will list all commits, the latest one on the top, together with username,email, time and comment about the commit.
echo -------

# the command's syntax
echo -e "\nCOMMAND SYNTAX:"
echo -e "\n\tgit log [options]"
echo -e "\t\t--author=<pattern>: Use the —author flag, if you need commits created by a particular user."
echo -e "\t\t--grep=<pattern>: Use the —grep flag, to filter commits by their commit message."

echo -e "\n------------"
