#!/usr/bin/env bash
echo -e git merge
echo git merge means join two development branches together. The main branch defaultly is called master. It is a pointer pointed the latest commited object.Once you make a commit, the master pointer will move to the new commited snapshot. Making a new branch is like making a new poiter to point to the latest committed snapshot. If you work on the new branch and make some changes, also the new branch and master branch have the same ancestor, git merge will just merge the changes together. If you make more than one commit in new branch, the two branches do not have the same ancestor. Then the merge operation will make a new commit for them to merge.
echo --------

# the command's syntax
echo -e "\nCOMMAND SYNTAX:"
echo -e "\n\tgit merge [options]"
echo -e "\t\t--abort: Will abort the merge process, and will try to reconstruct the pre-merge state."
echo -e "\t\t-m <msg>: Specify a message <msg> to be used for the merge commit."

echo -e "\n------------"
