#!/usr/bin/env bash

# The command's name
echo -e 'git init'

# the command's description
echo "git init initializes a new Git repository or reinitializes an existing one. If no argument is specifified, git init will perform on your present working directory.

git init converts your directory into a Git repository. It creates a .git folder and allows version control to start. When you reinitialize an existing repository, its commit history will be reset."

echo "------------"

# the command's syntax
echo "Syntax:"
echo "test argument1 argument2"
echo -e "\targument1: description of argument 1"
echo -e "\targument2: description of argument 2"
#   ...      etc

echo "------------"

# the command's usage examples
# example 1
echo "git init"
echo "Initializes a new git repository or reinitializes an existing one."

# example 2
echo "git init -q"
echo "Initializes a new git repository or reinitializes an existing one quietly. It will only print out error and warning messages."

# example 3
echo "git init --bare"
echo "Initializes a bare git repository. A bare git repository has no working directory and has no .git directory created. Instead the files normally in the .git repository is placed in the top-level directory where the working directory would normally be."

exit 0
