#!/usr/bin/env bash

# The command's name
echo -e 'git log'

# the command's description
echo "description here"

echo "------------"

# the command's syntax
echo "Syntax:"
echo "git log -3"
echo -e "\t-3: The number of outputs git log will display."

echo "------------"

# the command's usage examples
# example 1
echo "git test"
echo description here

# example 2
echo "git test something"
echo description here


exit 0
