#!/usr/bin/env bash

# The command's name
echo -e 'git merge'

# the command's description
echo "description here"

echo "------------"

# the command's syntax
echo "Syntax:"
echo "git merge branch_name"
echo -e "\tbranch_name: The specified branch to merge into the current branch."

echo "------------"

# the command's usage examples
# example 1
echo "git test"
echo description here

# example 2
echo "git test something"
echo description here


exit 0
