#!/usr/bin/bash

# The command's name
echo -e 'git push'

# the command's description
echo "description here"

echo "------------"

# the command's syntax
echo "Syntax:"
echo "git test argument1 argument2"
echo -e "\targument1: description of argument 1"
echo -e "\targument2: description of argument 2"
#   ...      etc

echo "------------"

# the command's usage examples
# example 1
echo "git push origin master"
echo "This pushes the selected branch 'master' to the remote alias 'origin'. If the master branch exists on the remote it will be updated, otherwise it will be created."

# example 2
echo "git push origin"
echo "If no branch is specified it will default to pushing to the upstream branch, this may vary depending on you version of git. You can set the push.default in git config."


exit 0
