#!/usr/bin/env bash

# The command's name
echo -e 'git rebase'

# the command's description
echo "Rebasing is the process of moving a branch to a new base commit. Rebasing involves moving a branch from one commit to another. Internally, Git accomplishes this by creating new commits(replacing the commits from the branch being moved) and applying them to the specified base— literally rewriting the project history.

The primary reason for rebasing is to maintain a linear project history and is a common way to integrate upstream changes into your local repository."

echo "------------"

# the command's syntax
echo "Syntax:"
echo
echo "git rebase [-i] [option] [branch]"
echo -e "\t[-i] - Sets up git for an interactive rebase."
echo -e "\t[option] - A command option or command flag."
echo -e "\t[option: --continue] - Restarts the rebasing process after a merge conflict has been resolved."
echo -e "\t[option: --abort] - Abandon the current rebasing process and return the repository to it's prior state."
echo -e "\t[branch]: The specified branch where the current branch will be re-written to."

echo "------------"

# the command's usage examples
# example 1
echo "git test"
echo description here

# example 2
echo "git test something"
echo description here


exit 0
