#!/usr/bin/env bash

# some formatting variables
bold="\033[1m"
underline="\033[4m"
normal="\033[0m"
# to use this formatting use 'echo -e'
# start formatting sequence with ${bold} or ${underline}
# and end it with ${normal}

# The command's name
echo -e "\n${bold}COMMAND NAME:${normal}"
echo -e "\n\t${bold}git rebase${normal}"

echo -e "\n------------"

# the command's description
echo -e "\n${bold}COMMAND DESCRIPTION:${normal}"


echo -e "\n\tgit rebase is a another command for two branches to merge. For instance,"
echo -e "\tuser is on the new branch, git rebase will get the diff introduced by each commit of"
echo -e "\tthis branch and save those diffs to temporary files, then reset the current branch"
echo -e "\tto the same commit as the branch user is rebasing on. git rebase command actually"
echo -e "\ttakes the changes from new branch and reapplies them on the branch user want to merge."

 echo -e "\n------------"

 # the command's syntax
echo -e "\n${bold}COMMAND SYNTAX:${normal}:"
echo -e "\n\tgit rebase [options]"
echo -e "\n\t\t-i: Interactive rebasing, with which you have an ability to alter commits \n\t\t    as they are moved to the new branch, mostly used for cleaning a messy history \n\t\t    before merging a feature branch into master."
echo -e "\t\t--abort: Will leave you where you were before attempting the rebase."

echo -e "\n------------"

# the command's usage examples
# example 1
echo -e "\n${bold}COMMAND EXAMPLES:${normal}"
echo -e "\n\t${underline}Example 1${normal}"
echo -e "\n\tgit rebase master new_feature"
echo -e "\n\t\tgit checkouts 'new_feature' branch, puts aside all commits that are created"
echo -e "\t\tsince 'new_feature' diverged from the master branch, then merges master branch"
echo -e "\t\tinto 'new_feature' branch and then reapplies commits from 'new_feature' that"
echo -e "\t\twere put aside."

# example 2
echo -e "\n\t${underline}Example 2${normal}"
echo -e "\n\tgit rebase -i upstream"
echo -e "\n\t\tthe same as above, but pulls changes from upstream repository to the current"
echo -e "\t\tworking branch using the interactive mode.\n"

#   ...      etc

exit 0
