#!/usr/bin/env bash

# some formatting variables
bold="\033[1m"
underline="\033[4m"
normal="\033[0m"
# to use this formatting use 'echo -e'
# start formatting sequence with ${bold} or ${underline}
# and end it with ${normal}

# The command's name
echo -e "\n${bold}COMMAND NAME:${normal}"
echo -e "\n\t${bold}git rm${normal} - remove files from the repository"

echo -e "\n------------"

# the command's description
echo -e "\n${bold}COMMAND DESCRIPTION:${normal}"
echo -e "\n\t'git rm' removes files from the index, or from the index and the working"
echo -e "\ttree. Files can not be removed only from the working tree with 'git rm'"
echo -e "\tand be left in the index. Files that you want to remove must be already"
echo -e "\tcommited and no changes of those files can be staged in the index, but that"
echo -e "\tcan be changed with ${bold}--cached${normal} option."
echo -e "\n\t'git rm' actually performs two actions in one go, first it removes the file"
echo -e "\tlike 'rm file' command will do, and then it adds that change to the index,"
echo -e "\tlike with 'git add file' so that the deletion will be commited."

echo -e "\n------------"

# the command's syntax
echo -e "\n${bold}COMMAND SYNTAX:${normal}"
echo -e "\n\tgit test argument1 argument2"
echo -e "\t\targument1: description of argument 1"
echo -e "\t\targument2: description of argument 2"
#   ...      etc

echo -e "\n------------"

# the command's usage examples
# example 1
echo -e "\n${bold}COMMAND EXAMPLES:${normal}"
echo -e "\n\t${underline}Example 1${normal}"
echo -e "\t\tgit test"
echo -e "\t\tdescription here"

# example 2
echo -e "\n\t${underline}Example 2${normal}"
echo -e "\t\tgit test something"
echo -e "\t\tdescription here\n"

#   ...      etc

exit 0
