#!/usr/bin/env bash

# The command's name
echo -e 'git rm'

# the command's description
echo "The git rm command removes files from the staging area and the working directory so that they will no longer be tracked by git.

This command differs from the command rm, where rm only deletes the file in the working directory, but git still keeps it in the staging area. Do take note."

echo "------------"

# the command's syntax
echo "Syntax:"
echo "git test argument1 argument2"
echo -e "\targument1: description of argument 1"
echo -e "\targument2: description of argument 2"
#   ...      etc

echo "------------"

# the command's usage examples
# example 1
echo "git rm file.txt"
echo "This will remove the file from the repository and directory while simultaneously staging the deletion, making the change ready to be committed in one command."

# example 2
echo "git rm -f sample.txt"
echo "-f will allow you to remove a file that has unstaged changes to it."


exit 0
