#!/usr/bin/env bash

# some formatting variables
bold="\033[1m"
underline="\033[4m"
normal="\033[0m"
# to use this formatting use 'echo -e'
# start formatting sequence with ${bold} or ${underline}
# and end it with ${normal}

# The command's name
echo -e "\n${bold}COMMAND NAME:${normal}"
echo -e "\n\t${bold}git status${normal} - show the working tree status"

echo -e "\n------------"

# the command's description
echo -e "\n${bold}COMMAND DESCRIPTION:${normal}"
echo -e "\n\t'git status' displays files that have differences between your last commit"
echo -e "\tand your current working tree. It shows files that are ready to be commited,"
echo -e "\tthe files that are changed but not added to the index and the files that are"
echo -e "\tnot tracked by Git and not ignored by '.gitignore' file."

echo -e "\n------------"

# the command's syntax
echo -e "\n${bold}COMMAND SYNTAX:${normal}"
echo -e "\n\tgit status [OPTIONS] [PATHSPEC]"
echo -e "\t\t-s: give the output in the short format."
echo -e "\t\t--long: give the output in the long-format. This is default."
echo -e "\t\t-u: show untracked files"
#   ...      etc

echo -e "\n------------"

# the command's usage examples
# example 1
echo -e "\n${bold}COMMAND EXAMPLES:${normal}"
echo -e "\n\t${underline}Example 1${normal}"
echo -e "\t\tgit test"
echo -e "\t\tdescription here"

# example 2
echo -e "\n\t${underline}Example 2${normal}"
echo -e "\t\tgit test something"
echo -e "\t\tdescription here\n"

#   ...      etc

exit 0
