#!/usr/bin/env bash

# some formatting variables
bold=$(tput bold)
underline="\033[4m"
normal=$(tput sgr0)
# to use this formatting use 'echo -e'
# start formatting sequence with ${bold} or ${underline}
# and end it with ${normal}

# The command's name
echo -e "\n${bold}COMMAND NAME:${normal}"
echo -e "\n\t${bold}git test${normal} - command used for git testing"

echo -e "\n------------"

# the command's description
echo -e "\n${bold}COMMAND DESCRIPTION:${normal}"
echo -e "\n\tThe 'git test' command is used for git testing...."

echo -e "\n------------"

# the command's syntax
echo -e "\n${bold}COMMAND SYNTAX:${normal}"
echo -e "\n\tgit test argument1 argument2"
echo -e "\t\targument1: description of argument 1"
echo -e "\t\targument2: description of argument 2"
#   ...      etc

echo -e "\n------------"

# the command's usage examples
# example 1
echo -e "\n${bold}COMMAND EXAMPLES:${normal}"
echo -e "\n\t${underline}Example 1${normal}"
echo -e "\t\tgit test"
echo -e "\t\tdescription here"

# example 2
echo -e "\n\t${underline}Example 2${normal}"
echo -e "\t\tgit test something"
echo -e "\t\tdescription here\n"

#   ...      etc

exit 0
