#!/usr/bin/env bash

# some formatting variables
bold="\033[1m"
underline="\033[4m"
normal="\033[0m"
# to use this formatting use 'echo -e'
# start formatting sequence with ${bold} or ${underline}
# and end it with ${normal}

# The command's name
echo -e "\n${bold}COMMAND NAME:${normal}"
echo -e "\n\t${bold}alias${normal} - create your custom command."

echo -e "\n------------"

# the command's description
echo -e "\n${bold}COMMAND DESCRIPTION:${normal}"
echo -e "\n\t'alias' command is used for command shortening, it's the easiest way to create your"
echo -e "\town custom command and minimize the typing effort. 'alias' command is only "
echo -e "\tavailable during the current working session and in order to save aliases for later use, "
echo -e "\tyou need to place it in the associated run control file (e.g. .bashrc). If 'alias' is "
echo -e "\tcreated with the same name as an existing executable program in your path, 'alias' will "
echo -e "\tbe used instead. To see all aliases available run 'alias' without any parameters."

echo -e "\n------------"

# the command's syntax
echo -e "\n${bold}COMMAND SYNTAX:${normal}"
echo -e "\n\talias [alias-name[=string]...]"
echo -e "\n\t\t${bold}alias-name${normal}:"
echo -e "\t\t\tthe name given to the alias."
echo -e "\n\t\t${bold}string${normal}:"
echo -e "\t\t\tstring or command that alias is bound to."
echo -e "\n\t\tThere are no options for 'alias' command."
#   ...      etc

echo -e "\n------------"

# the command's usage examples
# example 1
echo -e "\n${bold}COMMAND EXAMPLES:${normal}"
echo -e "\n\t${underline}Example 1${normal}"
echo -e "\t\ttest"
echo -e "\t\tdescription here"

# example 2
echo -e "\n\t${underline}Example 2${normal}"
echo -e "\t\ttest something"
echo -e "\t\tdescription here\n"

#   ...      etc

exit 0
