#!/usr/bin/env bash

# The command's name
echo -e "\nCOMMAND NAME:"
echo -e "\n\tcd - (c)hange (d)irectory"

echo -e "\n------------"

# the command's description
echo -e "\nCOMMAND DESCRIPTION:"
echo -e "\n\tThe 'cd' command changes the current working directory in the command line."
echo -e "\tAs argument it uses a path to the desired directory, either a relative path (e.g. 'cd path/to/the/directory')"
echo -e "\tor an absolute path (e.g. 'cd ~/projects')."
echo -e "\tIf 'cd' command is used without an argument it will try to use \$HOME environment variable as its argument."
echo -e "\tIf you use a dash as the argument ('cd -') you can go back to the previous active directory and the command"
echo -e "\twill output its path to the console."

echo -e "\n------------"

# the command's syntax
echo -e "\nCOMMAND SYNTAX:"
echo -e "\n\ttest argument1 argument2"
echo -e "\t\targument1: description of argument 1"
echo -e "\t\targument2: description of argument 2"
#   ...      etc

echo -e "\n------------"

# the command's usage examples
# example 1
echo -e "\nCOMMAND EXAMPLES:"
echo -e "\n\tExample 1"
echo -e "\t\ttest"
echo -e "\t\tdescription here"

# example 2
echo -e "\n\tExample 2"
echo -e "\t\ttest something"
echo -e "\t\tdescription here\n"

#   ...      etc

exit 0
