#!/usr/bin/env bash

# some formatting variables
bold="\033[1m"
underline="\033[4m"
normal="\033[0m"
# to use this formatting use 'echo -e'
# start formatting sequence with ${bold} or ${underline}
# and end it with ${normal}

# The command's name
echo -e "\n${bold}COMMAND NAME:${normal}"
echo -e "\n\t${bold}chmod${normal}"

echo -e "\n------------"

# the command's description
echo -e "\n${bold}COMMAND DESCRIPTION:${normal}"

echo -e "\n\tchmod stands for change mode, it is used to change the permissions of files or directories."
echo -e "\tIn the system,there are three kinds of permissions:read, write and executable. Also, there are"
echo -e "\tfour kinds of user groups: user who owns the files,users in the group to which the file belong,"
echo -e "\tusers are not in the file group, and all the other non-owner users. In the Unix-like system,"
echo -e "\tthere is a set of rules for each files which defines who can access that file, and how they can access it."
echo -e "\tSo chmode command is used to define the way a file can be accessed. "
echo -e "\n------------"

# the command's syntax
echo -e "\n${bold}COMMAND SYNTAX:${normal}:"
echo -e "\n\tchmod [ugoa...][+-=][rwx...] file"
echo -e "\t\tu: User who owns the file."
echo -e "\t\tg: Other users in the group to which the file belongs."
echo -e "\t\to: Users not in the file’s group."
echo -e "\t\ta: All users."
echo -e "\t\t[+-=]: Add, remove, set permissions."
echo -e "\t\t[rwx]: r - Read permission, w - Write permission, x - Execution permission."

echo -e "\n------------"

# the command's usage examples
# example 1
echo -e "\n${bold}COMMAND EXAMPLES:${normal}"

echo -e "\n\t${underline}Example 1${normal}"
echo -e "\n\tchmod ug+x file"
echo -e "\n\t\tmake 'file' executable for owner and the group that the 'file' belongs to."

# example 2
echo -e "\n\t${underline}Example 2${normal}"
echo -e "\n\tchmod a+r file1 file2 file3"
echo -e "\n\t\tmake 'file1', 'file2' and 'file3' readable for all users."

# example 3
echo -e "\n\t${underline}Example 3${normal}"
echo -e "\n\tchmod o-x file"
echo -e "\n\t\tremove executable permission from 'file' for all uses not in file's group."

# example 4
echo -e "\n\t${underline}Example 4${normal}"
echo -e "\n\tchmod g=rw file"
echo -e "\n\t\tmake 'file' readable and writable for other users in file's group and remove"
echo -e "\t\texecutable permission if it has it..\n"

#   ...      etc

exit 0
