#!/usr/bin/env bash

cat <<EOF

Name:
  clear

------------------------------------------------------------------------------

Description:
  Clear a command line screen/window for a fresh start.

------------------------------------------------------------------------------

Syntax:
  clear

------------------------------------------------------------------------------

Examples:
  clear

EOF

exit 0
