#!/usr/bin/env bash

# The command's name
echo -e 'cp'

# the command's description
echo "The cp command is used to make a copy of files and directories. The copies that are made are considered indepent from the originals, meaning that any changes made in the original will not affect the copy.

When a copy is made of a file or directory, the copy must have a different name than the original if it is to be placed in the same directory as the original. However, the copy can have the same name if it is made in a different directory."

echo "------------"

# the command's syntax
echo "Syntax:"
echo
echo "cp [option] [source] [destination]"
echo -e "\t[option] - a command option or command flag."
echo -e "\t[option: -R] - Enable cp to copy the entire directory from one place to another recursively."
echo -e "\t[option: -s] - Enable cp to create a symbolic link, where \033[4mdestination.txt\033[0m points to \033[4msource.txt\033[0m."
echo -e "\t[source] - Path of source file to be copied or symbolic linked."
echo -e "\t[destination] - Path of destination to where source file should be copied or symbolic linked to."

echo "------------"

# the command's usage examples
# example 1
echo "test"
echo description here

# example 2
echo "test something"
echo description here


exit 0
