#!/usr/bin/env bash

# The command's name
echo -e 'cp'

# the command's description
echo "description here"

echo "------------"

# the command's syntax
echo "Syntax:"
echo
echo "cp /path/to/source.txt /path/to/destination.txt"
echo -e "\t/path/to/source.txt: Source file to be copied."
echo -e "\t/path/to/destination.txt: Destination of where source file should be copied to."
echo
echo "cp -R /path/to/source-directory /path/to/destination-directory"
echo -e "\t-e: Enable cp to copy the entire directory from one place to another recursively."
echo -e "\t/path/to/source.txt: Source file to be copied."
echo -e "\t/path/to/destination.txt: Destination of where source file should be copied to."
echo
echo "cp -s /path/to/source.txt /path/to/destination.txt"
echo -e "\t-s: Enable cp to create a symbolic link, where \033[4mdestination.txt\033[0m points to \033[4msource.txt\033[0m."
echo -e "\t/path/to/source.txt: Source file to be copied."
echo -e "\t/path/to/destination.txt: Destination of where source file should be copied to."

echo "------------"

# the command's usage examples
# example 1
echo "test"
echo description here

# example 2
echo "test something"
echo description here


exit 0
