#!/usr/bin/bash

# The command's name
echo -e 'curl'

# the command's description
echo "description here"

echo "------------"

# the command's syntax
echo "Syntax:"
echo "git test argument1 argument2"
echo -e "\targument1: description of argument 1"
echo -e "\targument2: description of argument 2"
#   ...      etc

echo "------------"

# the command's usage examples
# example 1
echo "curl http://www.google.com"
echo "The following command will get the content of the URL and display it in the STDOUT on your terminal."

# example 2
echo "curl http://www.centos.org > centos-org.html"
echo "Will redirect the output and store in a file. Will also display download statistics"

# example 3
echo "$ curl -o getMyText.html http://www.gnu.org/software/gettext/manual/gettext.html"
echo "Will save the output to the file in the commandline. If us '-O' will use the same file name as that of the output"

#example 4
echo "curl URL1 URL2"
echo "Fetch Multiplec files"

#example 5
echo "curl -C - -O http://www.gnu.org/software/gettext/manual/gettext.html"
echo "If a download has stopped for whatever reason. You can use 'curl -C -' to continue the download."

#example 6
echo "curl --limit-rate 1000B -O http://www.gnu.org/software/gettext/manual/gettext.html"
echo "Limit the rate of the download to 1000 Bytes/second."

#example 7
echo "curl -u username:password URL"
echo "Pass HTTP authentication to the URL"

exit 0
