#!/usr/bin/env bash

# some formatting variables
bold="\033[1m"
underline="\033[4m"
normal="\033[0m"
# to use this formatting use 'echo -e'
# start formatting sequence with ${bold} or ${underline}
# and end it with ${normal}

# The command's name
echo -e "\n${bold}COMMAND NAME:${normal}"
echo -e "\n\t${bold}curl${normal} - transfer a URL"

echo -e "\n------------"

# the command's description
echo -e "\n${bold}COMMAND DESCRIPTION:${normal}"
echo -e "\n\t'curl' command is used for transfering data from or to a server"
echo -e "\tusing various protocols."
echo -e "\t'curl' offers many options, like user authentication, proxy support,"
echo -e "\tFTP upload, SSL connection, file transfer resume, etc."
echo -e "\n\tIn its simplest form it can be used like this to retrieve a web page,"
echo -e "\tthe '-L' option is used to follow the redirection if it occurs:"
echo -e "\te.g. 'curl -L google.com > google.html'"

echo -e "\n------------"

# the command's syntax
echo -e "\n${bold}COMMAND SYNTAX:${normal}"
echo -e "\n\tcurl [options] [URL...]"
echo -e "\t\t-a: when used in an FTP upload, this option will tell curl to append to the target file"
echo -e "\t\tinstead of overwriting it. If the file doesn\'t exist, it will be created."
echo -e "\t\t-L: this option will make the requestested page move to the new place."
#   ...      etc

echo -e "\n------------"

# the command's usage examples
# example 1
echo -e "\n${bold}COMMAND EXAMPLES:${normal}"
echo -e "\n\t${underline}Example 1${normal}"
echo -e "\t\tcurl -I google.com"
echo -e "\t\tUse '-I' option to get the headers from a specified website."

# example 2
echo -e "\n\t${underline}Example 2${normal}"
echo -e "\t\tcurl google.com > index.htm"
echo -e "\t\tFetch 'google.com' but redirect the output to a file 'index.htm', in the current directory.\n"

#   ...      etc

exit 0
