#!/usr/bin/env bash

cat<<EOF

Name:
  curl

------------------------------------------------------------------------------

Description:
  Display message on screen, writes each given STRING to standard output, with
  a space between each and a newline after the last one.

------------------------------------------------------------------------------

Syntax:
  echo [options]... [string]...

------------------------------------------------------------------------------

Options:
  -n  Do not output the trailing newline.

  -E  Disable the interpretation of the following backslash-escaped characters

  -e  Enable interpretation of the following backslash-escaped characters in
      each STRING:

      \a      alert (bell)

      \b      backspace

      \c      suppress trailing newline

      \e      escape

      \f      form feed

      \n      new line

      \r      carriage return

      \t      horizontal tab

      \v      vertical tab

      \\      backslash

      \NNN    The character whose ASCII code is NNN (octal); if NNN is not
              a valid octal number, it is printed literally.

      \xnnn   The character whose ASCII code is the hexadecimal value
              nnn (one to three digits)

------------------------------------------------------------------------------

Examples:
  echo -e "Hello World!"

EOF

exit 0
