#!/usr/bin/env bash

# some formatting variables
bold="\033[1m"
underline="\033[4m"
normal="\033[0m"
# to use this formatting use 'echo -e'
# start formatting sequence with ${bold} or ${underline}
# and end it with ${normal}

# The command's name
echo -e "\n${bold}COMMAND NAME:${normal}"
echo -e "\n\t${bold}exit${normal} - terminate shell or program"

echo -e "\n------------"

# the command's description
echo -e "\n${bold}COMMAND DESCRIPTION:${normal}"
echo -e "\n\t'exit' command is used to terminate the shell or program. Before logging you out from "
echo -e "\tthe running session, shell will always remind you, that some processes are currently "
echo -e "\tbeing active."

echo -e "\n------------"

# the command's syntax
echo -e "\n${bold}COMMAND SYNTAX:${normal}"
echo -e "\n\texit [${underline}n${normal}]"
echo -e "\t\t${underline}n${normal}: exit code number. Exit code number can have values form 0 to 255."
echo -e "\t\tIf no exit code number is provided to the 'exit' command it will default"
echo -e "\t\tto 0, i.e. 'success'. Any number above 0 is considered to be error."
echo -e "\t\tSome reserved exit codes:"
echo -e "\t\t\t0 - the command executed successfully"
echo -e "\t\t\t1 - there was an error executing the command"
echo -e "\t\t\t126 - a file to be executed was found, but it was not an executable utility"
echo -e "\t\t\t127 - a utility to be executed was not found"
echo -e "\t\t\t>127 - a command was interupted by a signal"

echo -e "\n------------"

# the command's usage examples
# example 1
echo -e "\n${bold}COMMAND EXAMPLES:${normal}"
echo -e "\n\t${underline}Example 1${normal}"
echo -e "\t\ttest"
echo -e "\t\tdescription here"

# example 2
echo -e "\n\t${underline}Example 2${normal}"
echo -e "\t\ttest something"
echo -e "\t\tdescription here\n"

#   ...      etc

exit 0
