#!/usr/bin/env bash
echo "This is the find command."

# The command's name
echo -e 'find'

# the command's description
echo "The find command is used to search for files and directories via the command line. It can be used to find files based on search criteria like name, ownership, date/time, size and much more. This command can also be used in conjunction with other commands to perform operations on the files that match the search results."

echo "------------"

# the command's syntax
echo "Syntax:"
echo "$ find [pathnames] [conditions]"
echo -e "\$ find -name "text1.txt": Find text1.txt file"
echo -e "\$find -maxdepth 2 -name "text1.txt": Find text1.txt file in the current directory and one level down to the current directory."
#   ...      etc

echo "------------"

# the command's usage examples
# example 1
echo "find . -name '*.txt'"
echo "search for all .txt files in the present working directory."

# example 2
echo "find -maxdepth 2 -d -name 'backups'"
echo "find all directory names that contain matching pattern, 'backups', in current directory and including one level down."


exit 0
