#!/usr/bin/env bash

# some formatting variables
bold="\033[1m"
underline="\033[4m"
normal="\033[0m"
# to use this formatting use 'echo -e'
# start formatting sequence with ${bold} or ${underline}
# and end it with ${normal}

# The command's name
echo -e "\n${bold}COMMAND NAME:${normal}"
echo -e "\n\t${bold}for${normal}"

echo -e "\n------------"

# the command's description
echo -e "\n${bold}COMMAND DESCRIPTION:${normal}"


echo -e "\n\tfor loop is a programming statement which allows a code block to be repeatly executed."
echo -e "\tThis loop allows for a specification of a list of values and a list of commands is executed for"
echo -e "\teach value in the list. At the end of loop, there gonna have a return status. Return status is"
echo -e "\tthe exit status of the last command executes. .This value, which is a integer between 0 to 255, "
echo -e "\tindicates the success or failure of the command's execution. A value of 0 means success and any other value"
echo -e "\t means failure. Usually, when the condition is not true,the loop will terminate with a non-zero exit status."
echo -e "\n------------"

# the command's syntax
echo -e "\nCOMMAND SYNTAX:"
echo -e "\n\tfor ITEM in LIST ; do ACTIONS ; done"
echo -e "\t\tITEM: Each item in a list."
echo -e "\t\tLIST: List of items you iterate through."
echo -e "\t\tACTIONS: Some commands you execute each iteration."

echo -e "\n------------"
