#!/usr/bin/env bash

# The concepts's name
echo -e 'for'

# the concept's description
echo "The for command is used to execute a for loop. A for loop operates on an array or a list of items repeating a set of commands for every item in the list. A for command can also be used to iterate through a numeric range."

echo "------------"

# the concept's syntax
echo -e "Syntax:\n"
echo -e "for i in \$( ls ); 
do
  echo item: \$i\n
done"
echo -e "\n\ti: Iteration item"

echo "------------"

# the concept's usage examples
# example 1
echo -e "for i in \$( ls ); do echo item: \$i\n; done"
echo "This example is the same as the for loop in the syntax section, but does everything on one line. It loops through all the filesystem objects (files, directories, ...) and echoes every item in a list."

# example 2
echo -e "for i do
			sum=$(($sum+$i))
		  done
		  printf \"$sum\n""
echo "This loop is part of script that accepts an arbitrary number of integers. It then calculates and prints the sum of the integers. Note that no range for the loop is specified. for loops use the number of arguments of a script as the default range to loop through if no range is specified."


exit 0
