#!/usr/bin/env bash

# The command's name
echo -e 'grep'

# the command's description
echo "description here"

echo "------------"

# the command's syntax
echo "Syntax:"
echo "grep \"string\" filename"
echo -e "\tstring: Search Pattern"
echo -e "\tfilename: The matched file where grep will be performed."
#   ...      etc

echo "------------"

# the command's usage examples
# example 1
echo "test"
echo description here

# example 2
echo "test something"
echo description here


exit 0
