#!/usr/bin/env bash
echo -e grep
echo grep ,which stands for global regular expression print, searches certain file globally and prints lines which match a specified regular expression.
echo -----

# the command's syntax
echo -e "\nCOMMAND SYNTAX:"
echo -e "\n\tgrep [options] pattern [files]"
echo -e "\t\t-r: Search recursively throught an entire directory tree."
echo -e "\t\t-v: Display all lines that do not match the search criteria (reverse of grep command)."
echo -e "\t\t-n: Display matched lines and their line numbers."

echo -e "\n------------"
