#!/usr/bin/env bash
echo "This is a test command."

# The command's name
echo -e 'ls'

# the command's description
echo "The ls command lists the contents of the specified argument, either a folder or file. If no argument is given the contents of the present working directory are shown."

echo "------------"

# the command's syntax
echo "Syntax:"
echo "test argument1 argument2"
echo -e "\targument1: description of argument 1"
echo -e "\targument2: description of argument 2"
#   ...      etc

echo "------------"

# the command's usage examples
# example 1
echo "test"
echo description here

# example 2
echo "test something"
echo description here


exit 0
