#!/usr/bin/env bash

# some formatting variables
bold="\033[1m"
underline="\033[4m"
normal="\033[0m"
# to use this formatting use 'echo -e'
# start formatting sequence with ${bold} or ${underline}
# and end it with ${normal}

# The command's name
echo -e "\n${bold}COMMAND NAME:${normal}"
echo -e "\n\t${bold}ls${normal} - list files or directories."

echo -e "\n------------"

# the command's description
echo -e "\n${bold}COMMAND DESCRIPTION:${normal}"
echo -e "\n\tIf invoked without any arguments, 'ls' command will list the files in the current directory."
echo -e "\tFiles will be listed without any details (e.g view details, file types, size, modified date and "
echo -e "\ttime, permission and links etc.). To be able to see the details, use different options available, most "
echo -e "\tuseful ones are -F, -R, -a, -l, and -s."

echo -e "\n------------"

# the command's syntax
echo -e "\n${bold}COMMAND SYNTAX:${normal}"
echo -e "\n\tls [option] [file]"
echo -e "\n\t\t${underline}option${normal}:"
echo -e "\n\t\t${bold}-a, --all${normal}:"
echo -e "\t\t\tshow hidden files, the ones starting with ."
echo -e "\n\t\t${bold}-h, --human_readable${normal}:"
echo -e "\t\t\tprint human readable file sizes, used with -l and/or -s options"
echo -e "\n\t\t${bold}-l${normal}: \tuse long listing format. Shows file permissions, sizes, owner, etc."
echo -e "\n\t\t${bold}-r, --reverse${normal}:"
echo -e "\t\t\treverse order while sorting"
echo -e "\n\t\t${bold}-R, --recursive${normal}:"
echo -e "\t\t\tlist subdirectories recursively"
echo -e "\n\t\t${bold}-s${normal}: \tprint allocated file sizes, in blocks"
echo -e "\n\t\t${bold}-S${normal}: \tsort by file size, largest first"
echo -e "\n\t\t${bold}-1${normal}: \tlist one file per line"
echo -e "\n\t\t${underline}file${normal}: the name of the directory to be listed. If omitted then the current directory is listed."
#   ...      etc

echo -e "\n------------"

# the command's usage examples
# example 1
echo -e "\n${bold}COMMAND EXAMPLES:${normal}"
echo -e "\n\t${underline}Example 1${normal}"
echo -e "\t\ttest"
echo -e "\t\tdescription here"

# example 2
echo -e "\n\t${underline}Example 2${normal}"
echo -e "\t\ttest something"
echo -e "\t\tdescription here\n"

#   ...      etc

exit 0
