#!/usr/bin/env bash
echo "This is the mv command."

# The command's name
echo -e 'mv'

# the command's description
echo "mv (Move) is a command to move one or more files or directories from one directory to another directory. It can also rename files or directories."

echo "------------"

# the command's syntax
echo "Syntax:"
echo "mv [options] <source> <destination>"
echo -e "\t-i: Prompt the user before overwriting "
echo -e "\t-n: Prevents overwriting of an existing file"
#   ...      etc

echo "------------"

# the command's usage examples
# example 1
echo "mv about-us.txt /home/my-projects"
echo "This command will move the file (about-us.txt) to the directory /home/my-projects."

# example 2
echo "mv file.txt life.txt"
echo "Using the mv command like this will rename a file called file.txt in the current directory to life.txt. "


exit 0
