#!/usr/bin/env bash
echo "This is a test command."

# The command's name
echo -e 'ping'

# the command's description
echo "The ping command is used to test the connection between a local computer/server and a remote server or host. 

Aside from checking connectivity, ping also tests the speed and reliability of a connection."

echo "------------"

# the command's syntax
echo "Syntax:"
echo "test argument1 argument2"
echo -e "\targument1: description of argument 1"
echo -e "\targument2: description of argument 2"
#   ...      etc

echo "------------"

# the command's usage examples
# example 1
echo "test"
echo description here

# example 2
echo "test something"
echo description here


exit 0
