#!/usr/bin/env bash

# The command's name
echo -e 'pipe'

# the command's description
echo "The pipe command is used to pass information from one command process to another. The benefit of using a pipe is that it provides for more complex processing than the use of just a single command. By providing a temporary direct connection between two or more simple programs it makes possible the performance of some highly specialized task that programs could not perform by themselves.

A pipe is specified by a vertical bar (|) in the command line. Insead of diplaying the output to the monitor, the result of the first command sequence is redirected to be used as the input for the second command sequence."

echo "------------"

# the command's syntax
echo "Syntax:"
echo "[command1] | [command2]"
echo -e "\t[command1] - The output of the command to pipe into command2."
echo -e "\t[command2] - command2 will use the output of command1 as input."

echo "------------"

# the command's usage examples
# example 1
echo "test"
echo description here

# example 2
echo "test something"
echo description here


exit 0
