#!/usr/bin/env bash
echo "This is the pwd command."

# The command's name
echo -e 'pwd'

# the command's description
echo "description here"

echo "------------"

# the command's syntax
echo "Syntax:"
echo "test argument1 argument2"
echo -e "\targument1: description of argument 1"
echo -e "\targument2: description of argument 2"
#   ...      etc

echo "------------"

# the command's usage examples
# example 1
echo "To print current working directory"
echo "$ pwd" 
echo "/Users/Neverland/documents/test"

# example 2
echo "$ x=$(pwd)"
echo "$ The current working directory : $x"
echo "The current working directory : /Users/Neverland/documents/test"


exit 0
