#!/usr/bin/env bash

# The command's name
echo -e 'ssh'

# the command's description
echo "description here"

echo "------------"

# the command's syntax
echo "Syntax:"
echo "git test argument1 argument2"
echo -e "\targument1: description of argument 1"
echo -e "\targument2: description of argument 2"
#   ...      etc

echo "------------"

# the command's usage examples
# example 1
echo "ssh jhawkins@collie.stanford.edu"
echo "Login to a remote host on which you have an account under the same user name as the host you're currently logged into"

# example 2
echo "ssh jhawkins@collie.stanford.ed"
echo "Login to a remote host on which you have an account under a different user name than the host you're current logged into:"

# example 3 
echo "ssh -V"
echo "Identify ssh client version."
exit 0
