#!/usr/bin/env bash

# The command's name
echo -e sudo'

# the command's description
echo "description here"

echo "------------"

# the command's syntax
echo "Syntax:"
echo "git test argument1 argument2"
echo -e "\targument1: description of argument 1"
echo -e "\targument2: description of argument 2"
#   ...      etc

echo "------------"

# the command's usage examples
# example 1
echo "sudo ls /usr/local/protected"
echo "Well get the file listing of an unreadable directory. Using the sudo command will override the directories permissions."

# example 2
echo "sudo -v"
echo "This will extend sudo's automatic authentication timeout, allowing you to continue issuing sudo commands without entering a password."

# example 3
echo "sudo -k"
echo "This will 'kill' sudo authentication for the current user. The next sudo command will require a password."

# example 4
echo "sudo -u john vi ~john/webdocs/index.html"
echo "Allow you to edit the index.html file with vi as the user john"

# example 5
echo "sudo apt-get install {package-name}"
echo "This command will install packages with the root privileges."

# example 6
echo "sudo apt-get remove {package-name}"
echo "This command will remove packages with the root privileges."

# example 7
echo "sudo apt-get update {package-name}"
echo "This command will update packages with the root privileges."

exit 0
