#!/usr/bin/env bash

# some formatting variables
bold="\033[1m"
underline="\033[4m"
normal="\033[0m"
# to use this formatting use 'echo -e'
# start formatting sequence with ${bold} or ${underline}
# and end it with ${normal}

# The command's name
echo -e "\n${bold}COMMAND NAME:${normal}"
echo -e "\n\t${bold}tar${normal}"

echo -e "\n------------"

# the command's description
echo -e "\n${bold}COMMAND DESCRIPTION:${normal}"

echo -e "\n\ttar stands for tape archive. Originally, it was used to backup files to taped-based storage"
echo -e "\tdevices.Nowadays, it is used to collect,distribute and archive files together with keeping" 
echo -e "\tfile system attributes such as user name, acess and modification dates, and directory"   
echo -e "\tstructures. In short, tar is to combine a few files into a single file, for easy storage and distribution."

# the command's syntax
echo -e "\nCOMMAND SYNTAX:"
echo -e "\n\ttar [options] archive-name files-to-archive"
echo -e "\t\t-c: Create archive from the specified files"
echo -e "\t\t-x: Extract the contents of a tar archive."
echo -e "\t\t-t: List the contents of a tar archive."

echo -e "\n------------"
