#!/usr/bin/env bash
echo -e tar
echo tar stands for tape archive. Originally, it was used to backup files to taped-based storage devices.Nowadays, it is used to collect,distribute and archive files together with keeping file system attributes such as user name, acess and modification dates, and directory structures. In short, tar is to combine a few files into a single file, for easy storage and distribution.

# the command's syntax
echo -e "\nCOMMAND SYNTAX:"
echo -e "\n\ttar [options] archive-name files-to-archive"
echo -e "\t\t-c: Create archive from the specified files"
echo -e "\t\t-x: Extract the contents of a tar archive."
echo -e "\t\t-t: List the contents of a tar archive."

echo -e "\n------------"
