#!/usr/bin/env bash

# some formatting variables
bold="\033[1m"
underline="\033[4m"
normal="\033[0m"
# to use this formatting use 'echo -e'
# start formatting sequence with ${bold} or ${underline}
# and end it with ${normal}

# The command's name
echo -e "\n${bold}COMMAND NAME:${normal}"
echo -e "\n\t${bold}tar${normal} - tape archive"

echo -e "\n------------"

# the command's description
echo -e "\n${bold}COMMAND DESCRIPTION:${normal}"

echo -e "\n\ttar stands for tape archive. Originally, it was used to backup files to taped-based storage"
echo -e "\tdevices. Nowadays, it is used to collect, distribute and archive files together with keeping"
echo -e "\tfile system attributes such as user name, access and modification dates, and directory"
echo -e "\tstructures. In short, tar is to combine a few files into a single file, for easy storage and distribution."

echo -e "\n------------"

# the command's syntax
echo -e "\n${bold}COMMAND SYNTAX:${normal}:"
echo -e "\n\ttar [options] archive-name files-to-archive"
echo -e "\n\t\t-c: Create archive from the specified files."
echo -e "\t\t-x: Extract the contents of a tar archive."
echo -e "\t\t-t: List the contents of a tar archive."

echo -e "\n------------"

# the command's usage examples
# example 1
echo -e "\n${bold}COMMAND EXAMPLES:${normal}"
echo -e "\n\t${underline}Example 1${normal}"
echo -e "\n\ttar -czf site_project_backup.tar ~/site_project/*.html ~/site_project/*.js ~/site_project/*.css"
echo -e "\n\t\tcreate a backup archive named 'site_project_backup.tar' in the current working"
echo -e "\t\tdirectory that contains all html, javascript and css files from 'site_project'"
echo -e "\t\tdirectory and filter it through 'gzip' program."

# example 2
echo -e "\n\t${underline}Example 2${normal}"
echo -e "\n\ttar -tf site_project_backup.tar"
echo -e "\n\t\tshow the contents of the 'site_project_backup.tar' archive file."

# example 3
echo -e "\n\t${underline}Example 3${normal}"
echo -e "\n\ttar -xzf site_project_backup.tar -C ~/new_project/"
echo -e "\n\t\textract the contents of the 'site_project_backup.tar' archive file into"
echo -e "\t\t'~/new_project/' directory.\n"

#   ...      etc

exit 0
