#!/usr/bin/env bash

# The command's name
echo -e "\nCOMMAND NAME:"
echo -e "\n\ttest - command used for testing"

echo -e "\n------------"

# the command's description
echo -e "\nCOMMAND DESCRIPTION:"
echo -e "\n\tThe 'test' command is used for testing...."

echo -e "\n------------"

# the command's syntax
echo -e "\nCOMMAND SYNTAX:"
echo -e "\n\ttest argument1 argument2"
echo -e "\t\targument1: description of argument 1"
echo -e "\t\targument2: description of argument 2"
#   ...      etc

echo -e "\n------------"

# the command's usage examples
# example 1
echo -e "\nCOMMAND EXAMPLES:"
echo -e "\n\tExample 1"
echo -e "\t\ttest"
echo -e "\t\tdescription here"

# example 2
echo -e "\n\tExample 2"
echo -e "\t\ttest something"
echo -e "\t\tdescription here\n"

#   ...      etc

exit 0
