#!/usr/bin/env bash
echo -e 'touch'
echo 'touch is a command which is used to change the modification or access date of a file. If that file does not exist,it equals to create that file with current time and 0 length. If that file exists, it will update the modification or access date of this file based on specific option requirement called flag.'
echo '--------'

# the command's syntax
echo -e "\nCOMMAND SYNTAX:"
echo -e "\n\ttouch [options] [date] files"
echo -e "\t\t-a: update only the access time"
echo -e "\t\t-m: update modification time only"
echo -e "\t\t-t: creates a file using a specified time,\n\t\t in format [[cc ]yy ]mmddhhmm [.ss ]"

echo -e "\n------------"
