#!/usr/bin/env bash
# some formatting variables
bold=$(tput bold)
underline="\033[4m"
normal=$(tput sgr0)
# to use this formatting use 'echo -e'
# start formatting sequence with ${bold} or ${underline}
# and end it with ${normal}

# The command's name
echo -e "\n${bold}COMMAND NAME:${normal}"
echo -e "\n\t${bold}touch${normal}"

echo -e "\n------------"

#commmand des
echo -e "\n${bold}COMMAND DESCRIPTION:${normal}"
echo -e '\n\ttouch is a command which is used to change the modification or access date of a file. If that file does not exist,it equals to create that file with current time and 0 length. If that file exists, it will update the modification or access date of this file based on specific option requirement called flag.'
echo -e '\n--------'

# the command's syntax
echo -e "\nCOMMAND SYNTAX:"
echo -e "\n\ttouch [options] [date] files"
echo -e "\t\t-a: update only the access time"
echo -e "\t\t-m: update modification time only"
echo -e "\t\t-t: creates a file using a specified time,\n\t\t in format [[cc ]yy ]mmddhhmm [.ss ]"

echo -e "\n------------"
