#!/usr/bin/env bash

# The command's name
echo -e 'wc'

# the command's description
echo "description here"

echo "------------"

# the command's syntax
echo "Syntax:"
echo ""
echo "wc -l filename"
echo -e "\t-l: Enable wc to print the number of newlines."
echo -e "\tfilename: The file where wc will be performed."
echo
echo "wc -w filename"
echo -e "\t-w: Enable wc to print the word count of a file."
echo -e "\tfilename: The file where wc will be performed."
echo
echo "wc -c filename"
echo -e "\t-w: Enable wc to print the total number of bytes in a file."
echo -e "\tfilename: The file where wc will be performed."

echo "------------"

# the command's usage examples
# example 1
echo "test"
echo description here

# example 2
echo "test something"
echo description here


exit 0
