#!/usr/bin/env bash

# some formatting variables
bold="\033[1m"
underline="\033[4m"
normal="\033[0m"
# to use this formatting use 'echo -e'
# start formatting sequence with ${bold} or ${underline}
# and end it with ${normal}

# The command's name
echo -e "\n${bold}COMMAND NAME:${normal}"
echo -e "\n\t${bold}wc${normal} - Count lines, words, and characters."

echo -e "\n------------"

# the command's description
echo -e "\n${bold}COMMAND DESCRIPTION:${normal}"
echo -e "\n\t'wc' command is used for counting words, characters, number of lines or files. The"
echo -e "\tmost common options are: count the number of words (-w flag), characters (-m), number"
echo -e "\tof lines (-l). It's often used together with pipe and redirection."

echo -e "\n------------"

# the command's syntax
echo -e "\n${bold}COMMAND SYNTAX:${normal}"
echo -e "\n\twc [option]... [${underline}file${normal}]..."
echo -e "\twc [option]... --files0-from=${underline}f${normal}"
echo -e "\n\t\twith no ${underline}file${normal}, or when ${underline}file${normal} is '-', read standard input"
echo -e "\n\t\t${bold}-c, --bytes${normal}:"
echo -e "\t\t\tprint byte counts"
echo -e "\n\t\t${bold}-m, --chars${normal}:"
echo -e "\t\t\tprint character counts"
echo -e "\n\t\t${bold}-l, --lines${normal}:"
echo -e "\t\t\tprint newline counts"
echo -e "\n\t\t${bold}-w, --words${normal}:"
echo -e "\t\t\tprint word counts"
echo -e "\n\t\t${bold}--files0-from=${underline}f${normal}:"
echo -e "\t\t\tread input from the files specified by NUL-terminated names in file ${underline}f${normal}."
echo -e "\t\t\tWhen the file ${underline}f${normal} is '-', then read names from standard input."

echo -e "\n------------"

# the command's usage examples
# example 1
echo -e "\n${bold}COMMAND EXAMPLES:${normal}"
echo -e "\n\t${underline}Example 1${normal}"
echo -e "\t\twc myfile.txt"
echo -e "\t\tdisplay info about the myfile.txt.The first number is number of lines,the second number is number of words."
echo -e "\t\tthe third number is the number of characters."

# example 2
echo -e "\n\t${underline}Example 2${normal}"
echo -e "\t\twc -w myfile.txt"
echo -e "\t\tpring the word counts of the file.\n"

#   ...      etc

exit 0
