#!/usr/bin/bash
echo "This is a wc command."

# The command's name
echo -e 'wc'

# the command's description
echo "wc - print the number of bytes, words, and lines in files"

echo "------------"

# the command's syntax
echo "wc -clmw my_file"
echo -e "\t-c: Print the number of bytes in each file"
echo -e "\t-l: Print the number of lines in each file"
echo -e "\t-m: Print the number of characters in each file"
echo -e "\t-w: Print the number of words in each file"
#   ...      etc

echo "------------"

# the command's usage examples
# example 1
echo "wc myfile.txt"
echo "Dispay number of lines, number of words and number of characters in myfile.txt"

# example 2
echo "ls | wc -cw"
echo "List all the files in current working directory and print the number of characters and number of words from the output generated by 'ls'"


exit 0
