#!/usr/bin/env bash

# The concepts's name
echo -e 'while'

# the concept's description
echo "The while command allows you to execute a 'While' loop, which executes one or many commands until the supplied condition no longer holds true. It is usually used when you need to manipulate the value of a variable repeatedly."

echo "------------"

# the concept's syntax
echo -e "Syntax:"
echo -e " 
COUNTER=0
while [  \$COUNTER -lt 10 ]; do
  echo Count Down \$COUNTER
  let COUNTER=COUNTER+1 
done
"

# the concept's usage examples
# example 1
echo -e " 
COUNTER=0
while [  \$COUNTER -lt 10 ]; do
  echo Count Down \$COUNTER
  let COUNTER=COUNTER+1 
done
"
echo "We set the COUNTER variable to 0. After this the loop starts and prints Count Down followed by the current value of COUNTER. Then it increases COUNTER's count by 1 and continues this process until the condition breaks (so until COUNTER is less than 10)."

exit 0
