#!/usr/bin/env bash

# some formatting variables
bold="\033[1m"
underline="\033[4m"
normal="\033[0m"
# to use this formatting use 'echo -e'
# start formatting sequence with ${bold} or ${underline}
# and end it with ${normal}

# The command's name
echo -e "\n${bold}COMMAND NAME:${normal}"
echo -e "\n\t${bold}whoami${normal} - who am I?"

echo -e "\n------------"

# the command's description
echo -e "\n${bold}COMMAND DESCRIPTION:${normal}"

echo -e "\n\twhoami is a command which will prints the effective username of the current"
echo -e "\tlogin user to the standard out, which usually is display screen."
echo -e "\n------------"

# the command's syntax
echo -e "\n${bold}COMMAND SYNTAX:${normal}:"
echo -e "\n\twhoami"
echo -e "\t\twhoami is mostly used by itself, without any options"

echo -e "\n------------"

# the command's usage examples
# example 1
echo -e "\n${bold}COMMAND EXAMPLES:${normal}"
echo -e "\n\t${underline}Example 1${normal}"
echo -e "\n\twhoami"
echo -e "\n\t\tprints the user name."

# example 2
echo -e "\n\t${underline}Example 2${normal}"
echo -e "\n\twhoami --help"
echo -e "\n\t\tdisplays help for the command."

# example 3
echo -e "\n\t${underline}Example 3${normal}"
echo -e "\n\twhoami --version"
echo -e "\n\t\tdisplays version of the command.\n"

#   ...      etc

exit 0
