#!/usr/bin/env bash
echo -e whoami
echo whoami is a command which will prints the effective username of the current login user to the standard out,which usually is display screen
echo ------

# the command's syntax
echo -e "\nCOMMAND SYNTAX:"
echo -e "\n\twhoami"
echo -e "\t\twhoami is mostly used by itself, without any options"

echo -e "\n------------"
